### ISSUE TITLE
Unexpected fields when creating customer

### ISSUE THREAD

**Issue by Tom5om** [adrienverge/localstripe#112]
When creating a customer I supply an address and phonenumber:

`stripe.customers.create({
        name: customerName,
        address: {
            line1: addressline,
            state: state
        },
        phone: "0400000000"
        email: "test@example.com"
    });`

It throws an error

![image](https://user-images.githubusercontent.com/4668890/71710085-9f1c9a00-2e4e-11ea-8f1c-062ca84a1cf4.png)

**Comment by Tom5om** [comment]
I am also getting unexpected trial_from_plan which is a way to create a customer with a trial specified in the plan

**Comment by adrienverge** [comment]
Hello @Tom5om, about your first problem, could you try https://github.com/adrienverge/localstripe/pull/113?

**Comment by Tom5om** [comment]
Hi Adrien, because of my other issue, I have had to move on and look for a different solution for my testing needs, sorry
