### ISSUE TITLE
start_date not set?

### ISSUE THREAD

**Issue by nnairtame** [adrienverge/localstripe#115]
It looks like the field start_date is not set for subscriptions. Per the [documentation](https://stripe.com/docs/api/subscriptions/object) I would expect it to default to the current time, but I am getting nulls back, and it does indeed look like the field is not implemented.

**Comment by adrienverge** [comment]
Indeed `start_date` is not implemented. Do you want to contribute to this project by adding it?

**Comment by nnairtame** [comment]
I'll see if I can get the time to do it at work.

Thank you for the project, it has been extremely helpful.

**Comment by adrienverge** [comment]
Fixed by #116.
