### ISSUE TITLE
Unable to create PaymentIntent

### ISSUE THREAD

**Issue by ImJustToNy** [adrienverge/localstripe#130]
Hello,
I'm using off_session charges to process subscriptions on my site. Problem is, when I use code such as:
```php
$payment = \Stripe\PaymentIntent::create([
    (...)
    'off_session' => true,
    'confirm' => true,
]);
```

I get an error regarding off_session and confirm parameters to be unexcepted.
Exact error: `Stripe\Exception\InvalidRequestException : Unexpected off_session, confirm`.
At first, I thought that it is lib-related problem, but that's not the case (switching to regular stripe API proves that code is correct as the intent is being created without any problem).

I would highly appreciate any help regarding that issue.

Best regards.

**Comment by adrienverge** [comment]
Hello Antoni,

Not all Stripe features are supported in localstripe, hence your failure.

Look the code and see supported parameters for `PaymentIntent`:
https://github.com/adrienverge/localstripe/blob/1ec76f1d23de9777635ba6bc57fe006223ae1c19/localstripe/resources.py#L1513-L1514

Do you want to contribute to the project by adding these parameters? A first step would be to just add them, without any handling.
