### ISSUE TITLE
Import/export state as a file

### ISSUE THREAD

**Issue by SamyPesse** [adrienverge/localstripe#145]
It'll be awesome to be able through an HTTP call (like the one to clear data) to export/import data from some JSON file.

This file will not be editable by hand, but just to make sure that localstripe can be started with existing data from a previous execution.

My usecase is basically we are running two sets of tests in different CI process (browser and unit tests) and they both use a common dataset for our main database, but this dataset is not in sync with localstripe.

**Comment by adrienverge** [comment]
Hey @SamyPesse, I understand the use-case and it seems legitimate. It seems a bit complicated to "hot load" some database state (I mean reset current data without killing+restarting the localstripe process) -- I'm not sure we would want to maintain such complexity.
If killing+restarting the localstripe process is not a problem to you, have you thought about saving `/tmp/localstripe.pickle` after an execution, then restoring it before starting localstripe again? (Internally, this is were cold data is saved.)

**Comment by SamyPesse** [comment]
Great! Yes killing/starting the process is not a problem.
It could be great to have a CLI option to specify another filepath

**Comment by SamyPesse** [comment]
Solution for people using localstripe with Docker:

```
docker run -p 8420:8420 -v ./stripe-data/:/tmp/ adrienverge/localstripe:latest
```
