### ISSUE TITLE
Support for latest stripe-js and react-stripe-js

### ISSUE THREAD

**Issue by SamyPesse** [adrienverge/localstripe#147]
`react-stripe-js` is doing a validation on the stripe object: https://github.com/stripe/react-stripe-js/blob/e13fae556b1a667a5dfa1130c00d5ec4c2bc154e/src/utils/guards.ts#L16

This validation is failing because of the missing `createPaymentMethod`

**Comment by adrienverge** [comment]
Thanks for reporting, I didn't know that.

If you want to contribute, you could add a dump JavaScript method [like this](https://github.com/adrienverge/localstripe/blob/f0a9400bd8be32edf03f6823ece872e295e033bd/localstripe/localstripe-v3.js#L216), and if you're motivated, implement it for real :+1:
