### ISSUE TITLE
Stripe Elements doesn't support single element

### ISSUE THREAD

**Issue by alessandro308** [adrienverge/localstripe#159]
As far as I see, Stripe elements doesn't support the api to fill a single field, like the real one does here https://github.com/stripe/elements-examples/blob/master/js/example2.js

Does it right?

**Comment by adrienverge** [comment]
That's highly probable; localstripe doesn't support much JavaScript compatibility. You can see all JS methods in https://github.com/adrienverge/localstripe/blob/7f8dd11/localstripe/localstripe-v3.js.
Contributions are welcome!
