### ISSUE TITLE
Missing resource paths

### ISSUE THREAD

**Issue by tarasyarema** [adrienverge/localstripe#163]
Hi, I began testing this mock server on our project and I noticed that the following resources return 404:
- `GET /v1/payouts`
- `GET /v1/balance`
- `GET /v1/invoiceitems`

My question is, am I doing something wrong or those are not implemented. If it's the second one, is it planned?

I'm using the Docker version of the server with the latest tag.

**Comment by H--o-l** [comment]
Hi @tarasyarema !

Only implemented APIs are the ones that contributors have contribute.
I don't know if anyone out there is planning to add the same route as you, but I think that If you are looking for new APIs chances are that you will have to make a pull request yourself.

Pull requests are quickly reviewed so once a pull request is open you will have community support until it's merged.
Keep in mind Git good practices: clear commit message and a commit should do only one thing. Don't add the three new routes in the same commit, or even the same pull request, split things as much as possible.

You can get an idea of what is currently implemented by looking here:
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/server.py#L267-L276
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L511-L512
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L511-L512
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L1362-L1366
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L1756-L1760
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L1929-L1931
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/localstripe/resources.py#L2292-L2294

If you decide to get involved here is a good starting point:
https://github.com/adrienverge/localstripe#hacking-and-contributing

And I suggest you use curl as much as possible as it's done inside unit tests:
https://github.com/adrienverge/localstripe/blob/591f3b5a62eccfbe86ac24a2b937dc047a46095a/test.sh

**Comment by tarasyarema** [comment]
Ok, cool. I will create a first PR with the `balance` object and see! Thanks for the quick reply!
