### ISSUE TITLE
Implement balance object

### ISSUE THREAD

**Issue by tarasyarema** [adrienverge/localstripe#164]
This issue will be to handle the `GET /v1/balance` resource.

**Comment by tarasyarema** [comment]
Hi @H--o-l, I implemented the `/v1/balance` resource. I'm planning on implementing the other resources I noted in the last issue #163. Wanted to know what is the cycle of PR acceptance.

**Comment by H--o-l** [comment]
Hi @tarasyarema ! Thanks ! 
I'm in holiday right now. Will look into it the 4th or 5th January

**Comment by tarasyarema** [comment]
Cool, just wanted to know, have nice holidays!

**Comment by adrienverge** [comment]
Hello @tarasyarema, thanks for your contributions. There is no need to open empty issues to track changes, especially if there are pull requests already. Let's follow this in #165.
