### ISSUE TITLE
stripe.error.InvalidRequestError: Unexpected source

### ISSUE THREAD

**Issue by drcongo** [adrienverge/localstripe#17]
Hi! Firstly thank you, localstripe is super helpful. Secondly, when trying to create a customer and passing a newly created token as the source, I'm getting back `stripe.error.InvalidRequestError: Unexpected source`.

Unpicking from the tests of a very large project, this is roughly all I'm doing (in Python)...

```
token = stripe.Token.create(
    card={
        "number": '4242424242424242',
        "exp_month": 12,
        "exp_year": 2056,
        "cvc": '123'
    }
)

stripe.Customer.create(
    email=user.email,
    source=token,
    description='{} {}'.format(user.firstname, user.lastname)
)
```

...where user is a valid user model factory. I suspect, like #7 that this might be down to the fact that the live API  endpoints on stripe.com handle older API versions to ease breaking changes but I'm not entirely sure. Any ideas?

edit: I also searched the source for the words "Unexpected source" and couldn't find them, which gave me the fear that somehow I was creating the token locally and then sending that to real Stripe.

**Comment by adrienverge** [comment]
Hi Andy, I'm glad localstripe is helpful to you!

It doesn't work because localstripe doesn't accept (yet) a `source` parameter into `stripe.Customer.create()`. No problem with the API version ;-)

I've just tried to fix this problem, can you test the [feat/customer-source](https://github.com/adrienverge/localstripe/commits/feat/customer-source) branch? If it works, I'll release a new version.

Adrien

**Comment by drcongo** [comment]
Tests passed! You sir, are a gentleman.

I now have an error later in the tests on creating a shared token (for Stripe Connect) but I guess we're getting into the darker corners of Stripe at this point. Feel free to close, and thank you.

**Comment by adrienverge** [comment]
Great! :)

About shared tokens, that's right, the logic behind it a bit more complicated and I feel we won't be able to implement all Stripe features in this lib :/

**Comment by drcongo** [comment]
No problem @adrienverge, hopefully one day I can find the time to help add some of the more esoteric features.

**Comment by maheshbist111** [comment]
hi ,
iam new to django. whin i procide for checkout i get error( stripe.error.InvalidRequestError: Request req_8P2QbLoX25IHKT: Invalid string: {
  "addre...d": null
}; must be at most 500 characters)
can any one help. 
Request Method: | POST
-- | --
http://127.0.0.1:8000/cart/checkout/
3.0.6
InvalidRequestError
Request req_8P2QbLoX25IHKT: Invalid string: {   "addre...d": null }; must be at most 500 characters
C:\Users\Mahesh\himalaya\lib\site-packages\stripe\api_requestor.py in handle_error_response, line 152
C:\Users\Mahesh\himalaya\Scripts\python.exe
3.7.4
['C:\\Users\\Mahesh\\himalaya\\ecommerce',  'C:\\Users\\Mahesh\\AppData\\Local\\Programs\\Python\\Python37-32\\python37.zip',  'C:\\Users\\Mahesh\\AppData\\Local\\Programs\\Python\\Python37-32\\DLLs',  'C:\\Users\\Mahesh\\AppData\\Local\\Programs\\Python\\Python37-32\\lib',  'C:\\Users\\Mahesh\\AppData\\Local\\Programs\\Python\\Python37-32',  'C:\\Users\\Mahesh\\himalaya',  'C:\\Users\\Mahesh\\himalaya\\lib\\site-packages']
Fri, 5 Jun 2020 12:55:48 +0000
