### ISSUE TITLE
No docker image available for version 1.13.5

### ISSUE THREAD

**Issue by 8byr0** [adrienverge/localstripe#201]
Hello there!

I just noticed that there's no tag `1.13.5` for your image `adrienverge/localstripe`. The latest push was 7 months ago for tag `1.13.4`.

Is there any manual action you need to perform?

Thanks !

**Comment by adrienverge** [comment]
Hello, sorry about that. I just fixed it :wink:

**Comment by 8byr0** [comment]
Great, thanks for being that responsive ! 🚀
