### ISSUE TITLE
'Free' Subscription on a customer with no source.

### ISSUE THREAD

**Issue by M0dM** [adrienverge/localstripe#36]
Hi @adrienverge ,

We should allow Subscription to a free Plan (Plan with amount=0) for a Customer who hasn't any Source.

It raises currencly an *InvalidRequestError*:
```stripe.error.InvalidRequestError: This customer has no source```

**Comment by adrienverge** [comment]
Since the introduction of `PaymentMethod`s in localstripe, this problem is fixed. Thus I'll close!
